### ISSUE TITLE
hey, it can't work in my env. Should I make some code changes?

### ISSUE THREAD

**Issue by DaveGeneral** [sophronesis/tsne_animate#1]
I install the tsne_animate, and download the FFmpeg to windows, add it to eviro Path, then, run it in Pycharm,  Meet the error:
Cannot save animation: no writers are available. Please install ffmpeg to save animations.
Then I change the __intial__.py  last line to 
 anim.save(filename, dpi=80, writer='ffmpeg')
it can't work either. 
please give some help, I'm going to  reinstall it

**Comment by DaveGeneral** [comment]
alright, I think I figure it out, change the __initial__.py  then install it. leave the trick to the latter

**Comment by sophronesis** [comment]
Hello @DaveGeneral,
In new version i fixed it
Try this:
1. On windows with anaconda for fast install of ffmpeg you can try
`$ conda install -c conda-forge ffmpeg`
2. You can save your animation like this:
```
anim = tsne.animate(digits.data,digits.target,return_anim=True)  
anim.save('temp.mp4', fps=20, codec='libx264')
```

Should work
(install it by git clone + setup, still need time to upload on PyPi)
